### ISSUE TITLE
How to send Data

### ISSUE THREAD

**Issue by laibulle** [stampzilla/gozwave#1]
Hi, 
I am trying your library as an alternative to the openzwave C++ implentation. Here is my code.

```
	z, err := gozwave.Connect("/dev/cu.usbmodem1411")
	if err != nil {
		panic(err)
	}

	go func() {
		time.Sleep(1 * time.Second)
		node := z.Nodes.Get(3)
		rollup := switchbinary.New().SetNode(node.Id()).SetValue(false)
		z.Connection.Send(rollup, time.Second*5)
	}()
```

but when I run it, I get this error. 

```
WARN[0001] Dropping message function='SendData' with data 0100 (not implemented)
```

Do you have an idea of the problem ?

**Comment by stamp** [comment]
Hi there!

The library is in a early stage so a lot of stuff is missing. The message you have there is just states that it received a "SendData" function message but we haven't made a decoder for the SendData function yet and is discarded. 

What hardware are you using? I have been using a usb connected controller from Aeon labs in linux environment.

**Comment by jonaz** [comment]
You can now do it like this:
```
node := z.Nodes.Get(3)
node.On()
```
In your example you should let i sleep for 10-20 seconds if you have many devices. Take a while to discover them.

I also added example on a small webservice which can be used to turn on or off devices: https://github.com/stampzilla/gozwave/blob/master/example/example.go
